### ISSUE TITLE
Reduce the number of variables after nopo decomp standalone and adjust some labels

### ISSUE THREAD

**Issue by mhamjediers** [mhamjediers/nopo_decomposition#12]
Keep maybe only the variables that indicate strata, weight, and matching indicator; rename to indicate that they belong to nopo

Ensure that it still works also as a postestimation command from kmatch

**Comment by maximilian-sprengholz** [comment]
- Implemented with `_nopo_matched`, `_nopo_mweight`, and `_nopo_strata` as labeled returns
- kmatch generated vars are dropped by default, which can be overridden by specifying `kmkeepgen` as option
-  `_nopo_mweight` and `_nopo_strata` are copies of the corresponding kmatch returns (you have doublettes if `kmkeepgen` is specified, but that approach keeps it clean and comprehensible)
- I added a check if the kmatch variables in `e(generate` and `e(wgenerate)` are still in the data when running `nopo decomp` - new calls after `estimates restore kmatch` do not work without `kmkeepgen` (in any case not the best idea, should be part of the help file)
