### ISSUE TITLE
Does it only work with one-to-many matching (nearest-single-neighbor-matching with replacemant?)

### ISSUE THREAD

**Issue by mhamjediers** [mhamjediers/nopo_decomposition#16]
If yes, the kmatch-postestimation should have a check and error message if not nn(1) or if wor (without replacement) specified

**Comment by maximilian-sprengholz** [comment]
The `wor` excemption makes sense to me, but everything else should be accomodated by the weights, no? Default in `kmatch md` is kernel matching with automatically determined bandwidth. Nearest neighbor matching has to be specifically requested via `nn(#)`.

**Comment by maximilian-sprengholz** [comment]
Does now abort after `kmatch md ..., nn() wor`:

```stata
// abort if matched without replacement (replacement necessary for correct weights)
if ("`e(wor)'" == "wor") {
	dis as error "nopo decomp requires matching with replacement. Option wor not allowed in:"
	dis as error " `_kmatch_cmdline'"
	error 322
	exit
}
```

Closing.
