### ISSUE TITLE
Cosmetic adjustments

### ISSUE THREAD

**Issue by mhamjediers** [mhamjediers/nopo_decomposition#17]
- [ ] matrix e(_N): adjust labels to group A and group B instead of "matched" and "controls"
- [x] Should we also display labels in matching-table of nopo decomp (instead of grp == 4)?
- [ ] what happens if one uses abbreviations of roptions in the kmatch-passthrough-option?

**Comment by maximilian-sprengholz** [comment]
- `_N` was a leftover from `kmatch` - I would omit it except when requested by `kmpassthru` (implemented in last commit). We could still return a table, but I doubt that it brings much more to the table than the returns we already have.
- Display is implemented, but with the `group == x` addition to be clear
- Dunno :D
