### ISSUE TITLE
option to change reference group and/or switch the weighting of the synthetic group

### ISSUE THREAD

**Issue by mhamjediers** [mhamjediers/nopo_decomposition#2]

**Comment by mhamjediers** [comment]
Maybe also add the option to make them all equal to one reference group of the by-groups

**Comment by maximilian-sprengholz** [comment]
At the moment implemented according to the ATT/ATC logic in `kmatch`. You feed a dummy (reverse by setting `tvalue` to something else than `1') and specify the reference group by setting either `atc` (= characteristics of controls, but beta of treated) or `att' (= characteristics of treated, but beta of controls).
