### ISSUE TITLE
Option to standardize wages as in nopomatch

### ISSUE THREAD

**Issue by mhamjediers** [mhamjediers/nopo_decomposition#3]

**Comment by mhamjediers** [comment]
Is implemented in the first setup of the main command; but shall we keep the variable? should be included also in the upper matching table?

**Comment by maximilian-sprengholz** [comment]
Having the kmatch dependency and two-step process, I guess we just document the approach we'd take if we want standardization and do not implement that option.

**Comment by maximilian-sprengholz** [comment]
Implemented as `NORMalize` option (normalize is the better term I think), for standalone only. Always normalized with respect to `bref' group and therefore changes with `treat` levels and `swap` (and, of course, `bref`).

Closing.
