### ISSUE TITLE
Post-command for comparison table with any variables across A(u), A(m), B(u), B(m), and B(weighted)

### ISSUE THREAD

**Issue by mhamjediers** [mhamjediers/nopo_decomposition#5]
(as in the Supplementary Materials or our submission)

**Comment by maximilian-sprengholz** [comment]
- [ ] define all necessary ereturns
- [ ] default for matching set; if varlist specified for varlist only
- [ ] think about export display vs. export options (check matrix label options)

**Comment by maximilian-sprengholz** [comment]
First version implemented with returned matrix. Still needs some nice SMCL output. Otherwise I think export is easy using, e.g., estout with matrices.

**Comment by maximilian-sprengholz** [comment]
Something for the roadmap, but would be nice to have: Specify which variables are factors and show the subgroups as shares (stats would be fixed in this case).

**Comment by maximilian-sprengholz** [comment]
Open for testing as `nopo summarize [varlist]`

**Comment by mhamjediers** [comment]
Can we do it with factor-variable notation? or do users just have to specify each level as dummy-variable?

**Comment by maximilian-sprengholz** [comment]
Factor handling is implemented:
- Factor notation is allowed when calling `nopo varlist`. Factor prefixes are stripped for `kmatch em` to circumvent factor variable error, all variables in `varlist` are treated as factors anyhow.
- Factor notation in `nopo` is passed through to `nopo summarize`. The shares of all factor levels are printed in %, other requested statistics are ignored.
- You can also directly use factor notation in `nopo summarize` to indicate factors (however, I guess this is rarely a good idea when the factors are not also indicated to kmatch)

Closing.
